# -*- coding: utf-8 -*-
"""Topsis for Pretrained Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A7kRbZTi6CR4583fAZAPetnsu-nG9QDq
"""



import matplotlib.pyplot as plt

Model = ['GPT-4', 'Gemini', 'Claude' ,'Mistral', 'LLaMA']
Score = [0.667113, 0.524808,  0.517930, 0.482266, 0.269973]

# Plot results
plt.figure(figsize=(8, 5))
plt.barh(ranked_results['Model'], ranked_results['Score'], color='skyblue')
plt.xlabel("TOPSIS Score")
plt.ylabel("AI Models")
plt.title("AI Model Ranking Based on TOPSIS")
plt.gca().invert_yaxis()
plt.savefig("topsis_ranking.png")
plt.show()